/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditLogDrawer: typeof import('./src/components/AuditLogDrawer.vue')['default']
    CategoryNode: typeof import('./src/components/CategoryNode.vue')['default']
    CategoryTree: typeof import('./src/components/CategoryTree.vue')['default']
    ConflictCompareDialog: typeof import('./src/components/ConflictCompareDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EnvironmentManager: typeof import('./src/components/EnvironmentManager.vue')['default']
    KeyValueEditor: typeof import('./src/components/KeyValueEditor.vue')['default']
    MockManager: typeof import('./src/components/MockManager.vue')['default']
    ProjectMemberManager: typeof import('./src/components/ProjectMemberManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamManager: typeof import('./src/components/TeamManager.vue')['default']
    VersionCompareDialog: typeof import('./src/components/VersionCompareDialog.vue')['default']
    VersionHistoryDrawer: typeof import('./src/components/VersionHistoryDrawer.vue')['default']
    WebSocketTester: typeof import('./src/components/WebSocketTester.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AuditLogDrawer: typeof import('./src/components/AuditLogDrawer.vue')['default']
  const CategoryNode: typeof import('./src/components/CategoryNode.vue')['default']
  const CategoryTree: typeof import('./src/components/CategoryTree.vue')['default']
  const ConflictCompareDialog: typeof import('./src/components/ConflictCompareDialog.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTimeline: typeof import('element-plus/es')['ElTimeline']
  const ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
  const EmptyState: typeof import('./src/components/EmptyState.vue')['default']
  const EnvironmentManager: typeof import('./src/components/EnvironmentManager.vue')['default']
  const KeyValueEditor: typeof import('./src/components/KeyValueEditor.vue')['default']
  const MockManager: typeof import('./src/components/MockManager.vue')['default']
  const ProjectMemberManager: typeof import('./src/components/ProjectMemberManager.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TeamManager: typeof import('./src/components/TeamManager.vue')['default']
  const VersionCompareDialog: typeof import('./src/components/VersionCompareDialog.vue')['default']
  const VersionHistoryDrawer: typeof import('./src/components/VersionHistoryDrawer.vue')['default']
  const WebSocketTester: typeof import('./src/components/WebSocketTester.vue')['default']
}